/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Stitch Design System Palette ──────────────────────────────────
        "outline": "#918fa1",
        "on-secondary-container": "#a7b6cc",
        "secondary-fixed": "#d4e4fa",
        "on-tertiary-container": "#d9d8ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "error": "#ffb4ab",
        "on-surface-variant": "#c7c4d8",
        "on-tertiary-fixed": "#07006c",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container": "#171f33",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed": "#0d1c2d",
        "surface-bright": "#31394d",
        "secondary": "#b9c8de",
        "on-secondary": "#233143",
        "on-primary": "#1d00a5",
        "inverse-on-surface": "#283044",
        "tertiary": "#c0c1ff",
        "outline-variant": "#464555",
        "on-primary-container": "#dad7ff",
        "tertiary-container": "#4b4dd8",
        "inverse-surface": "#dae2fd",
        "surface": "#0b1326",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-lowest": "#060e20",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "surface-container-low": "#131b2e",
        "secondary-container": "#39485a",
        "on-tertiary": "#1000a9",
        "secondary-fixed-dim": "#b9c8de",
        "tertiary-fixed": "#e1e0ff",
        "surface-container-high": "#222a3d",
        "surface-dim": "#0b1326",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#c0c1ff",
        "primary": "#c3c0ff",
        "surface-tint": "#c3c0ff",
        "background": "#0b1326",
        "inverse-primary": "#4d44e3",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#39485a",
        "primary-container": "#4f46e5",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
      animation: {
        "fade-in": "fadeIn 0.4s ease-out",
        "slide-up": "slideUp 0.35s ease-out",
        "slide-in-right": "slideInRight 0.35s cubic-bezier(0.32,0.72,0,1)",
        "pulse-slow": "pulse 3s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
};
